### ISSUE TITLE
JOSS review: about the paper

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [moldyn/msmhelper#32]
This is part of the review process for https://github.com/openjournals/joss-reviews/issues/5339

Hi and thanks for the work you have put into this nice package. Here is a list of comments related to the paper:

- [x] line 62: "Monte chain" -> "Markov chain" (I guess?)
- [ ] panels 1a, 1c and 1e look *extremely* similar to panels and figures of the Nagel et al (2023) paper. While this is not an issue per se, it may become a problem depending on the journal the foregoing paper will be published into. Please make sure that you'll have the rights to re-use the figure (or change the figure so that it won't clash with the journal license).
- [x] About the figure: while I appreciate brevity, I think here additional details about the quantities shown in the figures would help an interested (but maybe not too knowledgeable, or just inexperienced) reader

**Comment by braniii** [comment]
Thank you for taking the time to review our paper and for providing helpful feedback. We have addressed the first issue raised in your comments and corrected "Monte chain" to "Markov chain" in line 62. We agree that the third point is a good suggestion and will work to provide additional details about the quantities shown in the figures to improve the clarity of the paper. We appreciate the reviewer for raising the issue of potential copyright infringement related to the similarity of the figures in panels 1a, 1c, and 1e with those in Nagel et al (2023). We acknowledge that the origin of the similarity is due to the use of msmhelper, which is a crucial tool for generating the figures in our paper. We will take steps to address this concern.

**Comment by braniii** [comment]
Concerning the third point, the model in Nagel et al. (2023) has been updated for the final publication in JCTC. Hence, there should be no need for changing the figures here. We have also spotted another typo and added a short discussion of the figure.
