### ISSUE TITLE
JOSS Review--Code

### ISSUE THREAD

**Issue by yuxuanzhuang** [moldyn/msmhelper#33]
This is part of the review process for https://github.com/openjournals/joss-reviews/issues/5339

- state indexing
    - [x] I am a bit confused about how the state is indexed/reindexed. e.g. in [estimate_markov_model](https://github.com/moldyn/msmhelper/blob/5380ef761cb63f1d8e1bb4f28fd1e1087dd95314/src/msmhelper/msm/msm.py#L28). It is stated that "The states should start from zero" but I guess that's not necessary?
    
- ~~[plot_ck_test](https://github.com/moldyn/msmhelper/blob/5380ef761cb63f1d8e1bb4f28fd1e1087dd95314/src/msmhelper/plot/_ck_test.py#L21)~~
 ~~unfinished in the documentation~~

**Comment by braniii** [comment]
Thank you again for bringing these inconsistencies in the documentation to my attention. I apologize for any confusion that may have caused. You are correct that the states can be any integer and it is also possible to skip states. The error you noticed was due to a copy-paste error from an internal function that was optimized for performance. I appreciate your attention to detail and your feedback, which helps me improve the quality of this project.

**Comment by braniii** [comment]
Could you please provide more information about what you mean by "unfinished" in the second point of your previous feedback? In any case, I have updated the docstring of the chapman_kolmogorov_test function to make it clearer.

**Comment by yuxuanzhuang** [comment]
Sorry, I thought there was something missing in the second bracket but it seems to be functional on the documentation webpage.

**Comment by braniii** [comment]
I understand your query now. The notation [path.to.object][] is utilized in mkdocstrings syntax for the automatic generation of markdown references in the format [path.to.object](correct.html.path). This is a nice feature of the mkdocstrings package, which greatly aids in the creation of automated mkdocs documentations.

I've noted that you've taken off the 'Work in Progress' label. Consequently, I'll consider this issue resolved for the moment. However, if you encounter any additional issues, please don't hesitate to reopen this one. Your continued input is always appreciated.
